# Generated by Django 4.2.7 on 2024-02-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Slocation',
            new_name='slocation',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Sname',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Sprincipal',
            new_name='sprincipal',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Sage',
            new_name='sage',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Sname',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stname',
            new_name='stname',
        ),
    ]
