# Generated by Django 4.2.7 on 2024-02-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_slocation_school_slocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sage',
            new_name='stage',
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.school'),
        ),
    ]
